import * as path from 'path';
import * as vscode from 'vscode';
import { ConfigService } from '../services/ConfigService';

export function getTestFilePath(
    sourceFilePath: string,
    workspaceRoot: string,
    testOutputDir: string
): string {
    const relativePath = path.relative(workspaceRoot, sourceFilePath);
    const parsedPath = path.parse(relativePath);

    const testFileName = `test_${parsedPath.name}${parsedPath.ext}`;
    const testFilePath = path.join(
        workspaceRoot,
        testOutputDir,
        parsedPath.dir,
        testFileName
    );

    return testFilePath;
}

export function getTestFileDir(testFilePath: string): string {
    return path.dirname(testFilePath);
}

export async function ensureDirectoryExists(dirPath: string): Promise<void> {
    const uri = vscode.Uri.file(dirPath);
    try {
        await vscode.workspace.fs.stat(uri);
    } catch {
        await vscode.workspace.fs.createDirectory(uri);
    }
}

export function generateTestFileContent(
    imports: string[],
    testCode: string,
    sourceFilePath: string
): string {
    const uniqueImports = [...new Set(imports)];
    const importSection = uniqueImports.length > 0
        ? uniqueImports.join('\n') + '\n\n'
        : '';

    const header = `# Auto-generated unit tests for ${path.basename(sourceFilePath)}
# Generated by AI Unit Test Generator

`;

    return header + importSection + testCode;
}

export function extractPythonCodeBlock(content: string): string {
    const codeBlockRegex = /```python\n?([\s\S]*?)```/;
    const match = content.match(codeBlockRegex);

    if (match && match[1]) {
        return match[1].trim();
    }

    return content.trim();
}
